from __future__ import annotations

import argparse
import getpass
import os
import sys
from pathlib import Path

import yaml

from citedy_reddit_writer import __version__


def _prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    raw = input(f"{label}{suffix}: ").strip()
    return raw if raw else default


def _prompt_int(label: str, default: int) -> int:
    raw = _prompt(label, str(default))
    try:
        return int(raw)
    except ValueError:
        return default


def _prompt_bool(label: str, default: bool) -> bool:
    d = "y" if default else "n"
    raw = _prompt(f"{label} (y/n)", d).lower()
    return raw in ("y", "yes", "1", "true")


def _split_csv(s: str) -> list[str]:
    return [p.strip() for p in s.split(",") if p.strip()]


def _write_env(env_path: Path, api_key: str, config_rel: str) -> None:
    lines = [
        "# Generated by citedy-reddit-setup — do not commit.",
        f"CITEDY_AGENT_API_KEY={api_key}",
        f"CITEDY_REDDIT_CONFIG={config_rel}",
        "# Optional:",
        "# CITEDY_BASE_URL=https://www.citedy.com",
        "# CITEDY_REDDIT_TRANSPORT=auto",
        "# CITEDY_ALERT_WEBHOOK_URL=",
        "# DRY_RUN=0",
        "",
    ]
    env_path.write_text("\n".join(lines), encoding="utf-8")
    try:
        os.chmod(env_path, 0o600)
    except OSError:
        pass


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Interactive setup: writes config.yaml + .env (API key in .env only).",
    )
    parser.add_argument(
        "--dir",
        type=Path,
        default=Path.cwd(),
        help="Directory for config.yaml and .env (default: cwd)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing config.yaml / .env",
    )
    args = parser.parse_args(argv)

    base = args.dir.expanduser().resolve()
    base.mkdir(parents=True, exist_ok=True)
    cfg_path = base / "config.yaml"
    env_path = base / ".env"

    if cfg_path.exists() and not args.force:
        print(f"Refusing to overwrite {cfg_path} (use --force)", file=sys.stderr)
        return 2
    if env_path.exists() and not args.force:
        print(f"Refusing to overwrite {env_path} (use --force)", file=sys.stderr)
        return 2

    print(f"citedy-reddit-writer setup v{__version__}")
    print(f"Files will be written under: {base}\n")

    base_url = _prompt("Citedy base URL", "https://www.citedy.com").rstrip("/")
    print("Citedy Agent API key (Bearer citedy_agent_…, input hidden):")
    api_key = getpass.getpass("CITEDY_AGENT_API_KEY: ").strip()
    if not api_key:
        print("API key is required.", file=sys.stderr)
        return 2

    subs_raw = _prompt("Subreddits (comma-separated, no r/)", "SEO,bigseo")
    subs = _split_csv(subs_raw)
    if not subs:
        print("At least one subreddit required.", file=sys.stderr)
        return 2

    include_raw = _prompt("Include keywords (comma-separated)", "seo,google,ranking")
    exclude_raw = _prompt("Exclude keywords (comma-separated)", "nsfw,hiring")
    min_score = _prompt_int("Minimum Reddit score", 5)
    max_age_h = _prompt_int("Max post age (hours)", 72)
    listing = _prompt("Reddit listing (hot/new/top/rising)", "hot").lower()
    top_time = _prompt("If top: time window (hour/day/week/month/year/all)", "week").lower()
    per_sub = _prompt_int("Posts to fetch per subreddit (1-100)", 15)
    per_sub = max(1, min(100, per_sub))

    n_per_run = _prompt_int("Articles per run (max jobs this invocation)", 1)
    n_per_day = _prompt_int("Max articles per UTC day", 6)
    auto_pub = _prompt_bool("Auto-publish after generation", True)

    topic_tpl = _prompt(
        "Topic template ({title}, {subreddit}, {url})",
        "Original guide: address the discussion and search intent behind: {title} (context: r/{subreddit})",
    )

    doc: dict = {
        "citedy": {"base_url": base_url, "agent_api_key": ""},
        "reddit": {
            "transport": "auto",
            "user_agent": f"citedy-reddit-writer/{__version__} (automated)",
            "posts_per_subreddit": per_sub,
            "listing": listing,
            "top_time": top_time,
        },
        "subreddits": subs,
        "filters": {
            "include_keywords": _split_csv(include_raw),
            "exclude_keywords": _split_csv(exclude_raw),
            "min_score": min_score,
            "max_age_hours": max_age_h,
        },
        "run": {
            "articles_per_run": max(1, n_per_run),
            "max_articles_per_day": max(1, n_per_day),
            "topic_template": topic_tpl,
            "language": "en",
            "size": "standard",
            "mode": "standard",
            "wait_for_completion": False,
            "auto_publish": auto_pub,
            "disable_competition": False,
            "illustrations": False,
            "audio": False,
        },
        "dedupe": {
            "state_path": "./data/state.json",
            "max_tracked_post_ids": 800,
            "sync_recent_article_titles": True,
            "recent_articles_limit": 40,
        },
        "poll": {"interval_seconds": 15, "max_wait_seconds": 600},
        "logging": {"level": "INFO"},
    }

    cfg_path.write_text(
        yaml.dump(doc, default_flow_style=False, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )

    config_rel = str(cfg_path.name)
    _write_env(env_path, api_key, config_rel)

    print(f"\nWrote {cfg_path}")
    print(f"Wrote {env_path} (mode 0600)")
    print("\nNext runs:")
    print(f"  cd {base}")
    print("  set -a && source .env && set +a   # bash/zsh")
    print("  citedy-reddit-run --config config.yaml")
    print("\nDry-run (no API, no state writes):")
    print("  citedy-reddit-run --config config.yaml --dry-run")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
